Fixed build error in int32_publisher/app.c
The error was:
apps/int32_publisher/app.c.obj   -c /home/build/ws/firmware/freertos_apps/apps/int32_publisher/app.c
/home/build/ws/firmware/freertos_apps/apps/int32_publisher/app.c: In function 'timer_callback':
/home/build/ws/firmware/freertos_apps/apps/int32_publisher/app.c:25:2: error: implicit declaration of function 'UNUSED'; did you mean 'INTSET'? [-Werror=implicit-function-declaration]
  UNUSED(last_call_time);
  ^~~~~~
  INTSET
cc1: some warnings being treated as errors

Replaced the `UNUSED` macro with `RCLC_UNUSED`.